### ISSUE TITLE
Feature hardware control api

### ISSUE THREAD

**Issue by YGwan** [ecsimsw/JNI-JellyBean-HBE-SM5-S4210#5]
1. 키 입력
2. LED로 비트 표시
3. 7 - Segment 숫자 표시
4. LCD로 문자열 표시
5. 버저로 노래 출력
6. 진동 출력
7. Dot - Matrix로 문자열 표시

**Comment by ecsimsw** [comment]
left : Vibrator

LCD : clear and print
LED : bit reverse
