### ISSUE TITLE
Keypad Linux driver mapping on Android

### ISSUE THREAD

**Issue by ecsimsw** [ecsimsw/JNI-JellyBean-HBE-SM5-S4210#9]
`https://devse.tistory.com/6`

**Comment by YGwan** [comment]
![image](https://user-images.githubusercontent.com/50222603/173349694-02a35628-f886-49dd-bc41-0915e72a93d8.png)

**Comment by YGwan** [comment]
``` java
public static int[][] KEY_CODES = new int[][]{
        {44, 43, 37, 33},
        {45, 46, 48, 51},
        {53, 7, 8, 9},
        {10, 11, 12, 13}
};
```

![image](https://user-images.githubusercontent.com/50222603/173357578-a715b252-ddee-4264-94ea-09ebdc472cb6.png)
